version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: church-management-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  church-management:
    image: church-management:latest
    container_name: church-management
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - church_data:/data
    environment:
      - APP_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - DB_PATH=/data/church_management.db
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  church_data:
    driver: local
  redis_data:
    driver: local
