# Deno backend production service
version: '3.8'

services:
services:
  backend:
    image: denoland/deno:alpine-1.44.0
    container_name: deno-backend
    working_dir: /app
    volumes:
      - ./src:/app
    command: run --allow-net --allow-read main.ts
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DENO_ENV=production
